import type { Metadata } from "next";
import { headers } from "next/headers";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Header from "./ui/header";
import Footer from "./ui/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const pathname = headersList.get("pathname");
  let layout: any = (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
  if (pathname?.startsWith("/admin")) {
    layout = <>{children}</>;
  }

  return (
    <html lang="zh">
      <body>
        <AntdRegistry>{layout}</AntdRegistry>
      </body>
    </html>
  );
}
